### ISSUE TITLE
Choosing $ref as type makes the field disappear

### ISSUE THREAD

**Issue by sander-bol** [bjdash/JSON-Schema-Builder#1]
Steps to reproduce:

1. Choose $ref as the type for a property.
2. Watch the property disappear.

Console logs:
`https://bjdash.github.io/JSON-Schema-Builder/modules/JsonSchemeEditor/-schema.html - Failed to load resource: the server responded with a status of 404 (Not Found)`
`angular.js:13920 TypeError: Cannot read property '_type' of undefined`

**Comment by khorvat** [comment]
@bjdash do you plan to support the $ref any time soon?

**Comment by bjdash** [comment]
I am mostly done with the fix. Will commit in a day or two. Also I am adding some new features as well.

**Comment by khorvat** [comment]
That's great, thanks.

**Comment by bjdash** [comment]
Hi @sbol-coolblue, @khorvat,
I have fixed the issue with $ref. Please check if the issue is fixed and share your feedback.
